package com.grupo1.backend.entities.enums;

public enum CategoriaProducto {
    COMPONENTES, ORDENADORES, PERIFÉRICOS, GAMING_Y_VIDEOJUEGOS, 
    SMARTPHONES_Y_TABLETS, TELEVISORES, ELECTRODOMÉSTICOS, HOGAR, SONIDO, 
    RELOJES_INTELIGENTES, FOTOGRAFÍA, OCIO_Y_MOVILIDAD
}
